home/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from . import views

urlpatterns = [
    path('', views.home, name="homepage"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('sell/', views.ListingCreateView, name='sell'),
    path('buy', views.ListingListFilter.as_view(), name='buy'),
    path('search', views.search, name='search'),
    path('individual/<int:listing_id>', views.individual, name='individual'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hooshome/urls.py
from django.contrib import admin
from django.contrib.auth import views as authView
from django.urls import path, include
from django.conf import settings
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
]

home/models.py
import datetime
import json
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.utils import timezone


class Listing(models.Model):

    # Listing info
    description = models.TextField()
    pub_date = models.DateTimeField('date published', default=timezone.now)
    address = models.CharField(max_length=200)
    price = models.IntegerField()
    features = models.CharField(max_length=50, default="[]")
    beds = models.IntegerField(default=0)
    baths = models.IntegerField(default=0)
    front_View = models.ImageField(
        upload_to='media', default="media/vsabre.jpg")
    interior_View = models.ImageField(
        'Interior View', upload_to='media', default='media/vsabre.jpg')
    back_View = models.ImageField(
        'Back View', upload_to='media', default='media/vsabre.jpg')

    # Use Json to store lists as strings
    def set_features(self, x):
        self.features = json.dumps(x)

    def get_features(self):
        return json.loads(self.features)

    # Review info
    ratings = models.IntegerField(default=0)
    number_of_ratings = models.IntegerField(default=0)
    total_ratings = models.IntegerField(default=0)
    reviews = models.CharField(max_length=20000, default="[]")
    reviewers = models.CharField(max_length=19000, default="[]")

    # Use Json to store lists as strings
    def set_review(self, x):
        self.reviews = json.dumps(x)

    def get_review(self):
        return json.loads(self.reviews)

    def set_reviewer(self, x):
        self.reviewers = json.dumps(x)

    def get_reviewer(self):
        return json.loads(self.reviewers)

    def get_both(self):
        reviewers = self.get_reviewer()
        reviews = self.get_review()
        temp = []
        for i in range(min(len(reviews), len(reviews))):
            temp.append((reviews[i], reviewers[i]))

        return temp

    # Landlord info
    realtor_agent = models.CharField(max_length=200)
    realtor_site = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=15)

    def get_short_description(self):
        text = str(self.description)
        if len(text) < 200:
            print(len(text))
            return text + "‌‌ " * int((200 - len(text)) * 1.8)
        return text[:200] + "......"

    def __str__(self):
        return str(self.address) + " for " + str(self.price) + "\nDescription: " + str(self.description)

    def published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=50) <= self.pub_date <= now


class Users(models.Model):
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=30)

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Listing


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(
        max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(
        max_length=254, help_text='Required. Enter a valid email address.')


class SearchForm(forms.Form):
    search_text = forms.CharField(max_length=30, required=True)
    BEDS = (("1", "All Beds"), ("2", "1 Bed"),
            ("3", "2 Beds"), ("4", "3 Beds"), ("5", "3+ Beds"))
    BATHS = (("1", "All Baths"), ("2", "1 Bath"),
             ("3", "2 Baths"), ("4", "3 Baths"), ("5", "3+ Baths"))
    beds = forms.ChoiceField(choices=BEDS)
    baths = forms.ChoiceField(choices=BATHS)
    days = forms.ChoiceField(choices=[(x, x) for x in range(1, 5)])


class ListingForm(ModelForm):
    gym = forms.BooleanField(required=False)
    parking = forms.BooleanField(required=False)
    wifi = forms.BooleanField(required=False)
    heating = forms.BooleanField(required=False)
    furnished = forms.BooleanField(required=False)
    lounge = forms.BooleanField(required=False)
    laundry = forms.BooleanField(required=False)
    pets = forms.BooleanField(required=False)
    AC = forms.BooleanField(required=False)
    business_center = forms.BooleanField(required=False)

    temp = [(x, x) for x in range(1, 10)]

    baths = forms.ChoiceField(choices=temp)

    beds = forms.ChoiceField(choices=temp)

    class Meta:
        model = Listing
        fields = ('address', 'realtor_agent', 'description', 'front_View',
                  'interior_View', 'back_View', 'price', 'phone_number', 'realtor_site')

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.views.generic import CreateView, ListView
from .forms import SignUpForm, SearchForm, ListingForm
from .models import Listing
from django.shortcuts import get_object_or_404
from django.utils import timezone


class ListingList(ListView):
    template_name = 'home/index.html'
    context_object_name = 'all_listings'

    def get_queryset(self):
        """Returns recently published listings."""
        return Listing.objects.all()


class ListingListFilter(ListView):
    template_name = 'home/listing_filter.html'
    context_object_name = 'all_listings'

    def get_queryset(self):
        """Returns recently published listings."""
        return Listing.objects.all()


def search(request):
    if request.method == 'POST':
        key = request.POST['keyword']
        beds = request.POST.get('beds',False)
        baths = request.POST.get('baths',False)
        if key == "" and beds == "Number of Bedrooms" and baths == "Number of Bathrooms":
            return render(request, "home/search_results.html" )
        status = Listing.objects.filter(address__icontains=(key))
        if beds == "1 bed":
            status = status.filter(beds=1)
        elif beds == "2 beds":
            status = status.filter(beds=2)
        elif beds == "3 beds":
            status = status.filter(beds=3)
        elif beds == "3+ beds":
            status = status.filter(beds__gte=3)
        if baths == "1 bath":
            status = status.filter(baths=1)
        elif baths == "2 baths":
            status = status.filter(baths=2)
        elif baths == "3 baths":
            status = status.filter(baths=3)
        elif baths == "3+ baths":
            status = status.filter(baths__gte=3)

        return render(request, "home/search_results.html", {"buy": status})
    else:
        return render(request, "home/search_results.html")

def individual(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    if request.method == "POST":
        input = request.POST['input']
        rating = int(request.POST['rating'])
        if input == "" or input == None:
            return render(request, "home/listing_individual.html", {"listing": listing})

        listing.total_ratings += rating
        listing.number_of_ratings += 1
        listing.ratings = round(int(listing.total_ratings) / int(listing.number_of_ratings),2)
        print(rating)
        print(listing.number_of_ratings)

        temp_list = listing.get_review()
        temp_list.append(input)
        listing.set_review(temp_list)

        temp_list2 = listing.get_reviewer()
        temp_list2.append(request.user.username)
        #print(temp_list2)
        listing.set_reviewer(temp_list2)

        listing.save()

    return render(request, "home/listing_individual.html", {"listing": listing})

def home(request):
    if request.method == 'POST':
        key = request.POST['keyword']
        beds = request.POST.get('beds',False)
        baths = request.POST.get('baths',False)
        if key == "" and beds == "Number of Bedrooms" and baths == "Number of Bathrooms":
            return render(request, "home.html" )
        status = Listing.objects.filter(address__icontains=(key))
        if beds == "1 Bed":
            status = status.filter(beds=1)
        elif beds == "2 Beds":
            status = status.filter(beds=2)
        elif beds == "3 Beds":
            status = status.filter(beds=3)
        elif beds == "3+ Beds":
            status = status.filter(beds__gte=3)

        if baths == "1 Bath":
            status = status.filter(baths=1)
        elif baths == "2 Baths":
            status = status.filter(baths=2)
        elif baths == "3 Baths":
            status = status.filter(baths=3)
        elif baths == "3+ Baths":
            status = status.filter(baths__gte=3)

        return render(request,"home/listing_filter.html", {"all_listings": status})
    else:
        return render(request, "home.html")



def gitlink(request):
    link = redirect('https://github.com/UVA-CS3240-S19/project-102-nautilus')
    return link

def ListingCreateView(request):
    if not request.user.is_authenticated:
        return redirect('login')
    if request.method == 'POST':
        form = ListingForm(request.POST, request.FILES)
        temp = []
        if form["gym"].data == True:
            temp.append(0)
        if form["parking"].data == True:
            temp.append(1)
        if form["wifi"].data == True:
            temp.append(2)
        if form["heating"].data == True:
            temp.append(3)
        if form["furnished"].data == True:
            temp.append(4)
        if form["lounge"].data == True:
            temp.append(5)
        if form["laundry"].data == True:
            temp.append(6)
        if form["pets"].data == True:
            temp.append(7)
        if form["AC"].data == True:
            temp.append(8)
        if form["business_center"].data == True:
            temp.append(9)

        print(form["beds"].data)

        if form.is_valid():
            object = form.save()
            object.pub_date = timezone.now()
            object.beds = form["beds"].data
            object.baths = form["baths"].data
            object.set_features(temp)
            object.save()
            return redirect('/buy')
    else:
        form = ListingForm()
    return render(request, 'home/listing_form.html', {'form': form})

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

home/templates/home/listing_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<!-- Code template from https://bootsnipp.com/snippets/vl4R7 -->
<!DOCTYPE html>
<html>
{% load static %}
<head>
  <title>Create Listing</title>
  <!--Made with love by Mutiullah Samim -->

  <!--Bootsrap 4 CDN-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <!--Fontawesome CDN-->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
    integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

  <!--Custom styles-->
  <!-- <link rel="stylesheet" type="text/css" href="../../static/loginStyle.css"> -->
</head>

<div class="container-fluid">
		<div class="container">
			<div class="formBox">
				<form method="post" enctype="multipart/form-data">
                  {% csrf_token %}

						<div class="row">
							<div class="col-sm-12">
								<h1>Post your listing</h1>
							</div>
						</div>



						<div class="row">
							<div class="col-sm-6">
								<div class="inputBox ">
									<div class="inputText">Address</div>
                                  <div class="input">{{form.address}}</div>

								</div>
							</div>

							<div class="col-sm-6">
								<div class="inputBox">
									<div class="inputText">Realtor Agent</div>
                                  <div class="input">{{form.realtor_agent}}</div>
								</div>
							</div>
						</div>

						<div class="row">
							<div class="col-sm-6">
								<div class="inputBox">
									<div class="inputText">Price($/month)</div>
									<div class="input">{{form.price}}</div>
								</div>
							</div>

							<div class="col-sm-6">
								<div class="inputBox">
									<div class="inputText">Phone Number</div>
									<div class="input">{{form.phone_number}}</div>
								</div>
							</div>
						</div>
					<div class="row">
							<div class="col-sm-6">
								<div class="inputBox focus">
									<div class="inputText">Bedrooms</div>
									<div class="input">{{form.beds}}</div>
								</div>
							</div>

							<div class="col-sm-6">
								<div class="inputBox focus">
									<div class="inputText">Bathrooms</div>
									<div class="input">{{form.baths}}</div>
								</div>
							</div>
						</div>

						<div class="row">
							<div class="col-sm-12">
								<div class="inputBox">
									<div class="inputText">Website</div>
									<div class="input">{{form.realtor_site}}</div>
								</div>
							</div>
						</div>
											<div class="row">
							<div class="col-sm-12">
								<div class="inputBox">
									<div class="inputText">Description</div>
									<div class="input">{{form.description}}</div>
								</div>
							</div>
						</div>

                  <div class="panel-body" >
					<div class="panel-heading " >
						<h4 class="panel-title">
							<a data-toggle="collapse" href="#collapse1" class="text-center">
								<i class="indicator fas fa-dumbbell" aria-hidden="true"></i>Amenities
							</a>
						</h4>
					</div>
                </div>
<div id="collapse1" class="panel-collapse collapse in" >
                  <div class="row">

                    <div class="col-sm-3">{{form.gym}}<label>Fitness Center</label></div>
                    <div class="col-sm-3">{{form.parking}}<label>Parking</label></div>
                    <div class="col-sm-3">{{form.wifi}}<label>Internet Connection</label></div>
                    <div class="col-sm-3">{{form.furnished}}<label>Furnished</label></div>

                  </div>
                  <div class="row">

                    <div class="col-sm-3">{{form.lounge}}<label>Lounge</label></div>
                    <div class="col-sm-3">{{form.laundry}}<label>Laundry Room</label></div>
                    <div class="col-sm-3">{{form.pets}}<label>Pets Allowed</label></div>
                    <div class="col-sm-3">{{form.AC}}<label>Air Conditioner</label></div>

                  </div>
                  <div class="row">

                    <div class="col-sm-6">{{form.heating}}<label>Heating</label></div>
                    <div class="col-sm-6">{{form.business_center}}<label>Business Center</label></div>

                  </div>

</div>
                  <div class="panel-body" >
					<div class="panel-heading " >
						<h4 class="panel-title">
							<a data-toggle="collapse" href="#collapse2" class="text-center">
								<i class="indicator fas fa-images" aria-hidden="true"></i>Upload Images
							</a>
						</h4>
					</div>
                </div>
                  <div id="collapse2" class="panel-collapse collapse in" >
                                      <div class="row">
                    <div class="col-sm-4"><div class="inputText">Front View</div>{{form.front_View}}</div>
                    <div class="col-sm-4"><div class="inputText">Interior View</div>{{form.interior_View}}</div>
                    <div class="col-sm-4"><div class="inputText">Back View</div>{{form.back_View}}</div>
						</div>

                  </div>


<br>
						<div class="row">
							<div class="col-sm-12">
								<input type="submit" name="" class="button" value="Submit">
							</div>
						</div>
				</form>
			</div>
		</div>
	</div>

<style>
  body{
	margin: 0;
	padding: 0;
	font-family: sans-serif;
}
.formBox{
	margin-top: 90px;
	padding: 50px;
}
.formBox  h1{
	margin: 0;
	padding: 0;
	text-align: center;
	margin-bottom: 50px;
	text-transform: uppercase;
	font-size: 48px;
}
.inputBox{
	position: relative;
	box-sizing: border-box;
	margin-bottom: 50px;
}
.inputBox .inputText{
	position: absolute;
    font-size: 24px;
    line-height: 50px;
    transition: .5s;
    opacity: .5;
}
#id_address{
	position: relative;
	width: 100%;
	height: 50px;
	background: transparent;
	border: none;
    outline: none;
    font-size: 24px;
    border-bottom: 1px solid rgba(0,0,0,.5);
}
#id_price{
	position: relative;
	width: 100%;
	height: 50px;
	background: transparent;
	border: none;
    outline: none;
    font-size: 24px;
    border-bottom: 1px solid rgba(0,0,0,.5);
}

#id_beds{
	position: relative;
	width: 100%;
	height: 50px;
	background: transparent;
	border: none;
    outline: none;
    font-size: 24px;
    border-bottom: 1px solid rgba(0,0,0,.5);
}
#id_baths{
	padding-left: 40px;
	position: relative;
	width: 100%;
	height: 50px;
	background: transparent;
	border: none;
    outline: none;
    font-size: 24px;
    border-bottom: 1px solid rgba(0,0,0,.5);
}
#id_realtor_agent{
	position: relative;
	width: 100%;
	height: 50px;
	background: transparent;
	border: none;
    outline: none;
    font-size: 24px;
    border-bottom: 1px solid rgba(0,0,0,.5);
}
#id_realtor_site{
	position: relative;
	width: 100%;
	height: 50px;
	background: transparent;
	border: none;
    outline: none;
    font-size: 24px;
    border-bottom: 1px solid rgba(0,0,0,.5);
}
#id_phone_number {
	position: relative;
	width: 100%;
	height: 50px;
	background: transparent;
	border: none;
    outline: none;
    font-size: 24px;
    border-bottom: 1px solid rgba(0,0,0,.5);
}


.inputBox .input{
	position: relative;
	width: 100%;
	height: 50px;
	background: transparent;
	border: none;
    outline: none;
    font-size: 24px;


}
#id_description{
	position: relative;
	width: 500px;
	height: 500px;
	background: transparent;
    border: none;
    outline: none;
    font-size: 24px;

}
.focus .inputText{
	transform: translateY(-30px);
	font-size: 18px;
	opacity: 1;
	color: #00bcd4;

}
textarea{
	height: 100px !important;
}

.button {
	width: 100%;
    height: 50px;
    border: none;
    outline: none;
    background: #03A9F4;
    color: #fff;
}
</style>
<script src="https://code.jquery.com/jquery-3.2.1.js"></script>
	 <script type="text/javascript">
	 	 	$("#id_baths").focus(function() {
	 		$(this).parent().parent().addClass("focus");
	 	})
	 		 	$("#id_beds").focus(function() {
	 		$(this).parent().parent().addClass("focus");
	 	})
	 	$("#id_address").focus(function() {
	 		$(this).parent().parent().addClass("focus");
	 	})
	 		 	$("#id_phone_number").focus(function() {
	 		$(this).parent().parent().addClass("focus");
	 	})
	 		 	$("#id_realtor_agent").focus(function() {
	 		$(this).parent().parent().addClass("focus");
	 	})
	 		 	$("#id_price").focus(function() {
	 		$(this).parent().parent().addClass("focus");
	 	})
	 	$("#id_realtor_site").focus(function() {
	 		$(this).parent().parent().addClass("focus");
	 	})
	 		 		 	$("#id_description").focus(function() {
	 		$(this).parent().parent().addClass("focus");
	 	})
	 function toggleChevron(e) {
		$(e.target)
				.prev('.panel-heading')
				.find("i.indicator")
				.toggleClass('fa-caret-down fa-caret-right');
	}
	$('#accordion').on('hidden.bs.collapse', toggleChevron);
	$('#accordion').on('shown.bs.collapse', toggleChevron);


</script>


{% endblock %}

home/templates/home/search_results.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="../../static/style.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<form action="" method="post">

    <input type="submit" value="Submit">
</form>
<main role="main">
    <link rel="stylesheet" type="text/css" href="../../static/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <section class="jumbotron text-center">
                              <div class="container">
                        <form action="#" method="post" novalidate="novalidate">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="row">
                                        <div class="col-lg-4 col-md-3 col-sm-12 p-0">
                                            <input name="keyword" type="text" class="form-control search-slt" placeholder="Keyword Search">
                                        </div>
                                          <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                                            <select name="beds" class="form-control search-slt" id="exampleFormControlSelect1">
                                                <option>Number of Bedrooms</option>
                                                <option>all beds</option>
                                                <option>1 bed</option>
                                                <option>2 beds</option>
                                                <option>3 beds</option>
                                                <option>3+ beds</option>
                                            </select>
                                        </div>
                                          <div class="col-lg-3 col-md-3 col-sm-15 p-0">
                                            <select name="baths" class="form-control search-slt" id="exampleFormControlSelect2">
                                                <option>Number of Bathrooms</option>
                                                <option>all baths</option>
                                                <option>1 bath</option>
                                                <option>2 baths</option>
                                                <option>3 baths</option>
                                                <option>3+ baths</option>
                                            </select>
                                        </div>
                                        <div class="col-lg-2 col-md-3 col-sm-12 p-0">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-primary">Search</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
        <div class="container">
          <h1 class="jumbotron-heading">Listings example</h1>
          <p class="lead text-muted">HOOS HOME</p>
          <p>
            <a href="#" class="btn btn-primary my-2">START ANOTHER APARTMENT SEARCH</a>
            <a href="#" class="btn btn-secondary my-2">GO BACK</a>
          </p>
        </div>
      </section>
    {% if filter %}
      <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
          {% for choice in filter %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{MEDIA_URL}}{{ choice.front_View.url }}" alt="Card image cap">
                <div class="card-body">

                    <h5 class="jumbotron-heading">{{choice.address}}</h5>
                    <span class="heading">User Rating</span>
                    <span class="fa fa-star {% if choice.ratings > 0 %}checked{% endif %}"></span>
                    <span class="fa fa-star {% if choice.ratings > 1 %}checked{% endif %}"></span>
                    <span class="fa fa-star {% if choice.ratings > 2 %}checked{% endif %}"></span>
                    <span class="fa fa-star {% if choice.ratings > 3 %}checked{% endif %}"></span>
                    <span class="fa fa-star {% if choice.ratings > 4 %}checked{% endif %}"></span>
                  <p class="card-text">{{choice.description}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">More Info</button>
                    </div>
                      <small class="text-muted">{{choice.beds}} Beds</small>
                      <small class="text-muted">{{choice.baths}} Baths</small>
                    <small class="text-muted">${{choice.price}}/Month</small>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}




          </div>
        </div>
      </div>
    {% else %}
     <h5 class="jumbotron-heading">NO RESULTS FOUND</h5>
    {% endif %}

    </main>
{% endblock %}

home/templates/home/search_with_simple.html
{% extends "base.html" %}

{% block content %}
{% load static %}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->



<section class="search-sec">
    <div class="container">
        <form action="#" method="post" novalidate="novalidate">
            <div class="row">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                            <input type="text" class="form-control search-slt" placeholder="Enter Pickup City">
                        </div>
                          <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                            <select class="form-control search-slt" id="exampleFormControlSelect1">
                                <option>Number of Bedrooms</option>
                                <option>Example one</option>
                                <option>Example one</option>
                                <option>Example one</option>
                                <option>Example one</option>
                                <option>Example one</option>
                                <option>Example one</option>
                            </select>
                        </div>
                          <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                            <select class="form-control search-slt" id="exampleFormControlSelect2">
                                <option>Number of Bathrooms</option>
                                <option>Example one</option>
                                <option>Example one</option>
                                <option>Example one</option>
                                <option>Example one</option>
                                <option>Example one</option>
                                <option>Example one</option>
                            </select>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                            <button type="button" class="btn btn-danger wrn-btn">Search</button>
                        </div>
                      <div class="col-lg-2 col-md-2 col-sm-12 p-0">
                            <button type="button" class="btn btn-danger wrn-btn">More Options</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>

<br><br>
{% endblock %}